### ISSUE TITLE
DGPR model - kernel/weave error

### ISSUE THREAD

**Issue by SebastianPopescu** [thangbui/geepee#20]
Hi Thang,

So I am using the Deep Gaussian Process for a regression task and I get the following error:

Traceback (most recent call last):
  File "DGP_patches.py", line 42, in <module>
    mb_size=mb_size, adam_lr=0.001)
  File "../geepee/base_models.py", line 101, in optimise
    callback=callback)
  File "../geepee/utils.py", line 100, in adam
    f, g = func(x, *args)
  File "../geepee/utils.py", line 45, in __call__
    params_dict, idxs, alpha=alpha, prop_mode=prop_mode)
  File "../geepee/aep_models.py", line 921, in objective_function
    mout[i - 1], vout[i - 1])
  File "../geepee/aep_models.py", line 134, in forward_prop_thru_cav
    return self._forward_prop_random_thru_cav_mm(mx, vx)
  File "../geepee/aep_models.py", line 195, in _forward_prop_random_thru_cav_mm
    2 * self.ls, 2 * self.sf, mx, vx, self.zu)
  File "../geepee/kernels.py", line 229, in compute_psi_weave
    type_converters=weave.converters.blitz)
  File "/home/spopescu/.local/lib/python2.7/site-packages/weave/inline_tools.py", line 366, in inline
    **kw)
  File "/home/spopescu/.local/lib/python2.7/site-packages/weave/inline_tools.py", line 496, in compile_function
    verbose=verbose, **kw)
  File "/home/spopescu/.local/lib/python2.7/site-packages/weave/ext_tools.py", line 373, in compile
    verbose=verbose, **kw)
  File "/home/spopescu/.local/lib/python2.7/site-packages/weave/build_tools.py", line 242, in build_extension
    compiler_dir = platform_info.get_compiler_dir(compiler_name)
  File "/home/spopescu/.local/lib/python2.7/site-packages/weave/platform_info.py", line 125, in get_compiler_dir
    raise ValueError("The '%s' compiler was not found." % compiler_name)
ValueError: The 'gcc' compiler was not found.

I modified the code to ensure that the gcc compiler is used by default. If you go to platform_info.py it says that it's mostly useful on Windows. I am running it on a server which uses Ubuntu, do you think that's why it doesn't work?

**Comment by thangbui** [comment]
Hi Sebastian,

I have been running the code on Ubuntu and Mac and using weave 0.15.0, and I haven't seen this error.

So somehow weave doesn't use gcc by default or could not get the correct gcc path? What did you modify? 

Thang.

**Comment by SebastianPopescu** [comment]
solved...I should have installed weave via conda.
